services:
  postgres:
    image: postgres:12.15-alpine
    container_name: postgres_service
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local